apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: {{ .Release.Name }}
spec:
  template:
    serviceAccountName: argo
  dependencies:
    - name: {{ .Release.Name }}-dep
      eventSourceName: {{ .Release.Name }}
      eventName: git
      filters:
        data:
          - path: body.object_attributes.action
            type: string
            value:
              - open
              - update
  {{ tpl (.Files.Get (printf "files/%s.tpl" .Values.Trigger)) . }}
